# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1759, 1046)
        self.Bg_1 = QtWidgets.QLabel(Dialog)
        self.Bg_1.setGeometry(QtCore.QRect(-230, -90, 2001, 1171))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/Neuer Ordner/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Bg_2 = QtWidgets.QLabel(Dialog)
        self.Bg_2.setGeometry(QtCore.QRect(560, 60, 641, 461))
        self.Bg_2.setStyleSheet("\n"
"background-color: rgb(57, 57, 57);")
        self.Bg_2.setText("")
        self.Bg_2.setObjectName("Bg_2")
        self.Gif_1 = QtWidgets.QLabel(Dialog)
        self.Gif_1.setGeometry(QtCore.QRect(570, 70, 621, 441))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/Neuer Ordner/Iron_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Bg_3 = QtWidgets.QLabel(Dialog)
        self.Bg_3.setGeometry(QtCore.QRect(20, 90, 521, 411))
        self.Bg_3.setStyleSheet("\n"
"background-color: rgb(57, 57, 57);")
        self.Bg_3.setText("")
        self.Bg_3.setObjectName("Bg_3")
        self.Bg_4 = QtWidgets.QLabel(Dialog)
        self.Bg_4.setGeometry(QtCore.QRect(1220, 90, 521, 411))
        self.Bg_4.setStyleSheet("\n"
"background-color: rgb(57, 57, 57);")
        self.Bg_4.setText("")
        self.Bg_4.setObjectName("Bg_4")
        self.Gif_2 = QtWidgets.QLabel(Dialog)
        self.Gif_2.setGeometry(QtCore.QRect(30, 100, 501, 391))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/Neuer Ordner/Siri_1.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(Dialog)
        self.Gif_3.setGeometry(QtCore.QRect(1270, 140, 431, 321))
        self.Gif_3.setText("")
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Bg_5 = QtWidgets.QLabel(Dialog)
        self.Bg_5.setGeometry(QtCore.QRect(640, 550, 491, 201))
        self.Bg_5.setStyleSheet("\n"
"background-color: rgb(57, 57, 57);")
        self.Bg_5.setText("")
        self.Bg_5.setObjectName("Bg_5")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(1230, 100, 501, 391))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/Neuer Ordner/__02-____.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.Bg_6 = QtWidgets.QLabel(Dialog)
        self.Bg_6.setGeometry(QtCore.QRect(640, 760, 491, 201))
        self.Bg_6.setStyleSheet("\n"
"background-color: rgb(57, 57, 57);")
        self.Bg_6.setText("")
        self.Bg_6.setObjectName("Bg_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(1400, 970, 351, 61))
        self.label_3.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(227, 227, 227);\n"
"font: 8pt \"Lucida Calligraphy\";")
        self.label_3.setObjectName("label_3")
        self.pushButtonStart = QtWidgets.QPushButton(Dialog)
        self.pushButtonStart.setGeometry(QtCore.QRect(650, 560, 471, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStart.setFont(font)
        self.pushButtonStart.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.pushButtonQuit = QtWidgets.QPushButton(Dialog)
        self.pushButtonQuit.setGeometry(QtCore.QRect(650, 770, 471, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonQuit.setObjectName("pushButtonQuit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Made by Brandon Wohlwend</span></p></body></html>"))
        self.pushButtonStart.setText(_translate("Dialog", "Start"))
        self.pushButtonQuit.setText(_translate("Dialog", "Quit"))
#import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
